In [2]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])

cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [3]:
percentage = 100 * (A / cal.reshape(1,4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [4]:
for i in range(4):
    print(percentage[0][i])

94.91525423728814
0.0
2.8314028314028317
88.42652795838751


In [7]:
a = np.random.randn(5)
b = np.random.rand(5)

print(a)
print(b)

[ 0.60603312 -0.14939391 -1.06989748  2.70596306 -0.25825147]
[0.043827   0.13786371 0.44771257 0.10067844 0.56848374]


In [13]:
print(a.shape)##rank 1 array

(5,)


In [9]:
print(a.T)

[ 0.60603312 -0.14939391 -1.06989748  2.70596306 -0.25825147]


In [10]:
print(np.dot(a,a.T))##期待是一个矩阵，因为是列乘以行

8.923205218684535


In [18]:
a  = np.random.randn(5,1)
print(a)

[[-1.22559537]
 [-0.65938236]
 [-0.01971657]
 [ 0.66792368]
 [ 0.28859611]]


In [16]:
print(a.T)

[[ 1.80893594  1.35931768 -1.27044209 -1.1189969   0.27344483]]


In [17]:
print(np.dot(a,a.T))

[[ 3.27224924  2.4589186  -2.29814837 -2.02419371  0.49464417]
 [ 2.4589186   1.84774454 -1.7269344  -1.52107227  0.37169839]
 [-2.29814837 -1.7269344   1.61402312  1.42162077 -0.34739582]
 [-2.02419371 -1.52107227  1.42162077  1.25215407 -0.30598391]
 [ 0.49464417  0.37169839 -0.34739582 -0.30598391  0.07477207]]
